#!/usr/bin/env bash
# Usage: {SUB} commands
# Summary: List all {SUB} commands
# Help: This command is mostly used for autocompletion in various shells, and for `sub help`.
# Also, this command helps find commands that are named the same as potentially builtin shell commands (which, cd, etc)

set -e

. "$_SUB_ROOT/lib/colors.bash"

# Provide sub completions
if [ "$1" = "--complete" ]; then
  echo --sh
  echo --no-sh
  exit
fi

if [ "$1" = "--sh" ]; then
  sh=1
  shift
elif [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
fi

shopt -s nullglob

if [ "$1" != "--no-color" ]; then
  function color_fn { echo `clr_yellow $1`; }
else
  function color_fn { echo $1; }
fi
{ for path in ${SUB_COMMAND_PATH//:/$'\n'}; do
    for command in "${path}/"*; do
      command=$(basename $command)
    #   command="${command##*${SUB_COMMAND_PREFIX}-}"
      if [ -n "$sh" ]; then
        if [ ${command:0:3} = "sh-" ]; then
          echo -e `color_fn ${command##sh-}`
        fi
      elif [ -n "$nosh" ]; then
        if [ ${command:0:3} != "sh-" ]; then
          echo -e `color_fn ${command##sh-}`
        fi
      elif [ ${command:0:1} != "_" ]; then
        echo -e `color_fn ${command##sh-}`
      fi
    done
  done
  # all subs get `help` and `commands`
  echo `color_fn "help"`
  echo `color_fn "commands"`
} | sort | uniq
